name: GitHub Actions Test
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  production-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: main
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      - run: python3 main/main.py
